### ISSUE TITLE
Git-resolver cannot resolve the correct tag/commit hash with gitlab repo

### ISSUE THREAD

**Issue by huguesCarange** [pnpm/git-resolver#9]
## Expected Behavior

Resolve the correct tag/commit hash from the gitlab repo.

## Current Behavior

Resolve master/latest instead of desired tag/commit hash.

## Possible Solution
In parsePerf.js file, urlparse.hash is deleted before being used on line 35.
 -Deleted at line 45

My current solution: 
 Save urlparse.hash to a new variable before deleting it and use it later.

Ex at line 35: 
`const gitCommittish = setGitCommittish(urlparse.hash != null ? urlparse.hash.slice(1) : '');`
` return Object.assign({ fetchSpec: urlToFetchSpec(urlparse), normalizedPref: pref }, gitCommittish);`

## Steps to Reproduce
pnpm install git+http://gitlab.anygitlabrepo/team/anyproject.git#anyVersionTag
OR
pnpm install git+http://gitlab.anygitlabrepo/team/anyproject.git#anyCommitHash

## Context (Environment)
I do not know if it's related to my repository being private or only to gitlab/non-github repos. I did not test theses cases.

**Comment by etamponi** [comment]
Thanks for reporting :) there is a bug for it in the pnpm repository too (opened by me): https://github.com/pnpm/pnpm/issues/1127.

Thanks for pointing us at a possible solution too :)

**Comment by huochunpeng** [comment]
Could you try latest pnpm?
#12 should’ve fixed this.

**Comment by huguesCarange** [comment]
Nope didn't fixed it.
My test: 
pnpm install git+http://privateGitlabRepo/team/project#v0.1.19 (Not latest tag in repo)
Result:
Resolving: total 1, reused 0, downloaded 1, done
dependencies:
+ project 0.1.29 (Lastest tag in repo)

pnpm -i : 2.10.5

Thanks!

**Comment by huochunpeng** [comment]
@huguesCarange can u share your full url? I am not very familiar with gitlab, does it have special domain (rather than gitlab.com) for some private repo?

I suspect hosted-git-info did not recognize your url, which didn’t run the new code branch to normalize your url into ssh url. So your url was still handled by old code branch which uses the raw url.

**Comment by huguesCarange** [comment]
Unfortunately, I can't share my full url. This is the best I can do:
git+http://gitlab.pnpn.net/pnpm/git-resolver#v0.1.19

Thanks for the help and feel free to ask if I could help in any ways.

**Comment by huochunpeng** [comment]
Sure. That looks like an on-site local gitlab server, definitely not handled by hosted-git-info. So my PR has no effect.

**Comment by huguesCarange** [comment]
I just did the same test with a gitlab public repo and it worked flawlessly. 
Ex : pnpm install git+https://gitlab.com/gitm8/npmpty.git#v1.1.1 (Not latest)
Resolving: total 1, reused 0, downloaded 1, done

dependencies:
+ npmpty 1.1.1 (Worked)

**Comment by huguesCarange** [comment]
Yup, it's a private self-hosted/local gitlab repo.

Sorry if I didn't made that clear!

**Comment by huguesCarange** [comment]
@zkochan
Do you know when you will update git-resolver from 0.3.6 to 0.3.7 in the pnpm repo?
The fix is included in 0.3.7 right?

Thanks!

**Comment by zkochan** [comment]
when I updated it in the pnpm repo, tests in pnpm/packages/supi started to
fail.

**Comment by huochunpeng** [comment]
@zkochan what's the command to update deep dep git-resolver from supi directory? I was trying to see the failure.

**Comment by zkochan** [comment]
unfortunately, there is no such command at the moment but there is a
workaround. Add the version of git-resolver that you need as a dependency
of supi. Remove node_modules and shrinkwrap.yaml of supi. Run `pnpm
recursive link` in the root of pnpm.

**Comment by huochunpeng** [comment]
Right, I can see the errors now. But have no idea what's going on with the "unexpected store used".

From what I can see from the code of few failed test, it seems they are not related to git-resolver.

**Comment by zkochan** [comment]
ok, I'll check. If they are not related, I'll fix them
